departments = [
    "Galmeessa Siivilii",
    "Waajjira Invastimantii",
    "Bulchiinsaa fi Nageenya",
    "Waajjira Hojjataa fi Hawaasummaa",
    "Waajjira Aadaa fi Turiizimii",
    "Waajjira Milishaa",
    "Waajjira Dargaggoo fi Ispoortii",
    "Waajjira Karoora/Pilaanii fi Misoomaa",
    "Qajeelcha Poolisii",
    "Buusaa Gonofaa",
    "Abbaa Taayitaa Eegumsa Naannoo",
    "Abbaa Taayitaa Konistiraakshinii",
    "Koomishinii Turizimii",
    "Waajjira Lafaa",
    "Waajjira Fayyaa",
    "Waajjira Abbaa Alangaa",
    "Waajjira Saayinsii fi Teeknoloojii",
    "Waajjira Bishaan Dhugaatii fi Dhangala'aa",
    "Giddu-gala Tajaajilaa",
    "Waldaa Hojii Gamtaa",
    "Waajjira Albuuda",
    "Waajjira Dhimma Dubartootaa fi Daa'immanii",
    "Mana Qopheessaa",
    "Waajjira Galii",
    "Ejansii Geejjibaa",
    "Waajjira Kantiibaa",
    "Waajjira PSMQN",
    "Waajjira Kominikeeshinii",
    "Waajjira Daldala",
    "Waajjira Qonnaa",
    "Waajjira Maallaqaa",
    "Waajjira Carraa Hojii Uumuu fi Ogummaa",
    "Waajjira Barnoota"
]
